deployment:
  tasks:
    - export DEPLOYPATH=/home/ncyzekbm/public_html/
    - cd /home/ncyzekbm/repos/lechuzaruralasturias
    - echo "== Deploy start: $(date) =="
    - pwd
    - ls -la
    - if [ -f /home/ncyzekbm/nodevenv/repos/lechuzaruralasturias/20/bin/activate ]; then source /home/ncyzekbm/nodevenv/repos/lechuzaruralasturias/20/bin/activate; fi
    - node -v || true
    - npm -v || true
    - npm ci
    - npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/
    - if [ -f dist/.htaccess ]; then /bin/cp dist/.htaccess $DEPLOYPATH/; fi
    - echo "Despliegue EXITOSO: $(date)"