deployment:
  tasks:
    - DEPLOYPATH="/home/ncyzekbm/public_html"
    - echo "Iniciando copia de archivos..."
    - /bin/rm -rf "$DEPLOYPATH"/*
    - /bin/cp -R deploy/* "$DEPLOYPATH"/
    - echo "Despliegue completado: $(date)"
